version: "3.9"
services:
  frontend:
    build: ./frontend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
